### ISSUE TITLE
Partial wildcard matching

### ISSUE THREAD

**Issue by BReul** [pinojs/pino-noir#17]
My team leverages a few fields in our headers for authentication.  Namely
`x-api-key`, `x-api-secret`, and `x-api-password`

Currently, we can redact all of those by providing the three individual strings to pino, but I was wondering if there's a way we could use the wildcard character to pass pino something like `req.headers["x-api-*"]` instead?

**Comment by mcollina** [comment]
pino-noir is deprecated, please use the react functionality in pino itself.

This is not possible right now anyway.
