### ISSUE TITLE
Possible to redact partially?

### ISSUE THREAD

**Issue by mrchief** [pinojs/pino-noir#5]
Is it possible to redact partially, like the way credit card numbers or SSN number are done?

E.g.
```js
{ secret: "1234567890" } 

// outputs

{ secret: "xxxxxx7890" }
```

This will be very helpful to identify potential issues without delving the entire secret. 

I think the easiest and most flexible way would be to accept a function? Something like this:

```js
censor = (value) => {
// apply mask
return maskedValue
}
```

I understand this will cause a dip in performance which should be acceptable since this will be opt-in. And if there's a way to do it without sacrificing performance, even better!

Thoughts?

**Comment by davidmarkclements** [comment]
yes absolutely – I like it, we just need to ensure that there's no incidental performance hit on full redaction (e.g. ensure having to do a type of existence check doesn't reduce speed)

**Comment by davidmarkclements** [comment]
if you'd like to submit a PR (where censor can be a function) then it would be most welcome
