### ISSUE TITLE
Massive log messages

### ISSUE THREAD

**Issue by tbenade** [pinojs/pino-noir#8]
Quite possibly me but just thought I would check. Following the example for express in the readme.md, my log message post redaction is massive, essentially unusable.

This something I did or is that what to expect from pino-noir.

Thanks

**Comment by davidmarkclements** [comment]
could you please elaborate.. maybe show the output? 

there's no reason that *removing* values (or replacing them with "[Redacted]") should lead to huge log messages

perhaps this is more related to https://github.com/pinojs/express-pino-logger/issues/14

**Comment by davidmarkclements** [comment]
ok actually I think that's highly related, this is likely to do with req/res serializers not being applied in `pino-http`

I'll have a fix soon

**Comment by davidmarkclements** [comment]
see #13
